name: Deploy Website

on:
  push:
    branches: [main]   # Trigger only on main branch
    paths:
      - "index.html"   # Re-deploy if index.html changes
      - "images/**"    # Re-deploy if anything inside images/ changes
      - ".github/workflows/deploy.yml" # Re-deploy if workflow changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # root directory (contains index.html and images/)
