name: Deploy Portfolio Site

on:
  push:
    branches: [main]
    paths:
      - "index.html"
      - "css/**"
      - "fonts/**"
      - "images/**"
      - "js/**"
      - "lib/**"
      - "scss/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages   # explicitly set the branch for Pages
          publish_dir: .             # adjust if you add a build step later
          exclude_assets: |
            .DS_Store
            prepros-6.config

